# Generated by Django 3.2.5 on 2021-08-02 12:58

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('disable_in', models.DurationField(help_text='When to disable the user account. Blank values mean never disable', null=True)),
                ('device_validity_period', models.DurationField(help_text='Clearpass device expiry. Blank values mean never expire', null=True)),
                ('device_modified_warning_count', models.PositiveIntegerField(blank=True, help_text='Blank values mean never warn', null=True)),
            ],
            options={
                'verbose_name': 'User Type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='admin')),
                ('device_modified_count', models.PositiveIntegerField(default=0)),
                ('bypass_rate_limit', models.BooleanField(default=False, help_text='Rate limits help against brute force attacks, but cause issues when troubleshooting. Use with caution.')),
                ('disable_on', models.DateTimeField(blank=True, help_text='When to disable user account. Implicitly defined by user type.', null=True)),
                ('_device_validity_period', models.DurationField(blank=True, help_text='Implicitly defined by profile type. Write to override.', null=True)),
                ('_device_modified_warning_count', models.PositiveIntegerField(blank=True, help_text='Implicitly defined by profile type. Write to override.', null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='login.usertype')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
