# Generated by Django 4.0.6 on 2022-08-08 13:31

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import login.models.user
import macaddress.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()])),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether user should be treated as active. Unselect this instead of deleting accounts.')),
                ('mac_modifications', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=160, unique=True)),
                ('raw_value', models.CharField(max_length=160)),
                ('type', models.IntegerField(choices=[(0, 'Null'), (1, 'Boolean'), (2, 'Integer'), (3, 'String')])),
            ],
            options={
                'verbose_name': 'Permission',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'User Type',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=models.SET(login.models.user.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Type',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('mac_address', macaddress.fields.MACAddressField(integer=False, max_length=17, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('host', models.TextField()),
                ('logged_in', models.BooleanField(default=False)),
                ('mac_updated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=models.SET(login.models.user.get_sentinel_user), related_name='logins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login History',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.usertype'),
        ),
    ]
