# Generated by Django 3.2.6 on 2021-08-05 14:43

from django.db import migrations
import login.fields


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210803_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='_device_validity_period',
        ),
        migrations.RemoveField(
            model_name='usertype',
            name='device_validity_period',
        ),
        migrations.AddField(
            model_name='usertype',
            name='clearpass_device_expire',
            field=login.fields.WhenField(blank=True, max_length=16, null=True),
        ),
    ]
